INSERT INTO USERMANAGER.USERS (ID, USER_NAME, USER_AGE, USER_isAdmin, CREATED_DATA) VALUES ('1', 'Маша', '18', 'TRUE','18.02.83');
INSERT INTO USERMANAGER.USERS (ID, USER_NAME, USER_AGE, USER_isAdmin, CREATED_DATA) VALUES ('2', 'Миша', '18', 'TRUE','31.01.83');
INSERT INTO USERMANAGER.USERS (ID, USER_NAME, USER_AGE, USER_isAdmin, CREATED_DATA) VALUES ('3', 'Коля', '18', 'TRUE','13.03.83');
INSERT INTO USERMANAGER.USERS (ID, USER_NAME, USER_AGE, USER_isAdmin, CREATED_DATA) VALUES ('4', 'Настя', '18', 'TRUE','15.05.83');
INSERT INTO USERMANAGER.USERS (ID, USER_NAME, USER_AGE, USER_isAdmin, CREATED_DATA) VALUES ('5', 'Вася', '18', 'TRUE','07.04.83');